Repository AY2223S1-CS2103-F13-4/tp, pull requests merged in 2022-10, with the labels that each got.

#29 Add use cases in developer guide
  docs/DeveloperGuide.md
Labels: documentation

#30 Modify the general introduction and the add feature to add patients
  docs/UserGuide.md
Labels: documentation

#50 Add Photo and PPP
  docs/AboutUs.md
  docs/images/johnbenedictyan.png
  docs/johnbenedictyan.md
Labels: documentation

#51 Remove duplicate about us and move ppp to correct location
  docs/AboutUs.md
  docs/team/johnbenedictyan.md
Labels: documentation

#52 Update user guide to include delete command. Fixes #35. Fixes #38.
  docs/UserGuide.md
Labels: documentation

#32 Update user profile, proposition, and stories. Fixes #9
  docs/DeveloperGuide.md
Labels: documentation

#49 Update User Guide to include list command
  docs/UserGuide.md
Labels: documentation

#53 Update Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/mlzt2000.png
  docs/team/mlzt2000.md
Labels: documentation, check required

#64 Add ppp
  docs/team/lolfoollors.md
Labels: type.Documentation

#65 Implement Uid. Fixes #57
  src/main/java/seedu/address/logic/UidManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Uid.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#74 Modify exit message. Fixes #27.
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: type.Enhancement

#70 Implement and simplify Uid Manager operations. Fixes #69.
  src/main/java/seedu/address/logic/UidManager.java
  src/test/java/seedu/address/logic/UidManagerTest.java
Labels: type.Enhancement

#72 update userguide, helpwindow text, GUI logo and app name and add nurse category
  docs/UserGuide.md
  docs/images/helpMessageUpdated.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Nurse.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/healthcare_xpress_logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/CategoryTest.java
  src/test/java/seedu/address/model/person/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, enhancement

#68 Add implementation for list command to take in arguments
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/CategoryTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#82 Add Mark Command and testing
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Uid.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/VisitStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/model/person/VisitStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: check required

#114 Update help window
  src/main/java/seedu/address/ui/CommandNameListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/CommandNameListPanel.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement

#120 Fix minor bug in UpdateContactCommand
  src/main/java/seedu/address/logic/commands/UpdateContactCommand.java
Labels: priority.High, type.Bug

#121 Fix minor bugs
  src/main/java/seedu/address/logic/commands/UpdateContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateContactCommandParser.java
  src/test/java/seedu/address/logic/parser/UpdateContactCommandParserTest.java
Labels: bug, priority.High

#125 Update UG to include update contact command
  docs/UserGuide.md
Labels: type.Documentation
